"""empty message

Revision ID: 9aff44f8974d
Revises: 
Create Date: 2023-07-28 17:24:43.470067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aff44f8974d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_learning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Lot_size', sa.Float(), nullable=True),
    sa.Column('Year_built', sa.Float(), nullable=True),
    sa.Column('Overall_material', sa.Float(), nullable=True),
    sa.Column('Overall_condition', sa.Float(), nullable=True),
    sa.Column('Remodel_date', sa.Float(), nullable=True),
    sa.Column('Masonry_veneer', sa.Float(), nullable=True),
    sa.Column('First_Floor_square', sa.Float(), nullable=True),
    sa.Column('Second_Floor_square', sa.Float(), nullable=True),
    sa.Column('Above_grade_Area', sa.Float(), nullable=True),
    sa.Column('Full_bathrooms', sa.Float(), nullable=True),
    sa.Column('Number_Bedrooms_above_base', sa.Float(), nullable=True),
    sa.Column('Number_Kitchens', sa.Float(), nullable=True),
    sa.Column('Total_rooms_above_base', sa.Float(), nullable=True),
    sa.Column('Size_garage', sa.Float(), nullable=True),
    sa.Column('Pool_area', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_learning')
    # ### end Alembic commands ###
